import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  reference: [
    'overview',
    {
      type: 'category',
      label: 'Data types',
      collapsed: true,
      collapsible: true,
      link: {type: 'doc', id: 'datatypes-overview'},
      items: [
        'datatypes-datetime',
        'datatypes-variant',
        'datatypes-conversion',
      ],
    },
    {
      type: 'category',
      label: 'Commands',
      collapsed: true,
      collapsible: true,
      link: {type: 'doc', id: 'commands-overview'},
      items: [
        'stmt-query',
        {
          type: 'category',
          label: 'Query Operators',
          collapsed: true,
          collapsible: true,
          link: {type: 'doc', id: 'operators-overview'},
          items: [
            'operators-arithmetic',
            'operators-comparison',
            'operators-logical',
            'operators-set',
          ],
        },
        'stmt-ddl',
        'stmt-dml',
      ],
    },
    {
      type: 'category',
      label: 'Functions',
      collapsed: true,
      collapsible: true,
      link: {type: 'doc', id: 'functions-overview'},
      items: [
        {
          type: 'category',
          label: 'Aggregate',
          collapsed: true,
          collapsible: true,
          link: {type: 'doc', id: 'functions-aggregate'},
          items: [
            'functions/approx_quantile',
            'functions/avg',
            'functions/count',
            'functions/filter_nulls_max_by',
            'functions/filter_nulls_min_by',
            'functions/max',
            'functions/max_by',
            'functions/min',
            'functions/min_by',
            'functions/mode',
            'functions/stddev_pop',
            'functions/stddev_samp',
            'functions/sum',
            'functions/variance_pop',
            'functions/variance_samp',
          ],
        },
        {
          type: 'category',
          label: 'Conditional expression',
          collapsed: true,
          collapsible: true,
          link: {type: 'doc', id: 'functions-conditional'},
          items: [
            'functions/is-distinct-from',
            'functions/is-null',
          ],
        },
        'functions-conversion',
        {
          type: 'category',
          label: 'Date and time',
          collapsed: true,
          collapsible: true,
          link: {type: 'doc', id: 'functions-datetime'},
          items: [
            'functions/now',
            'functions/temporal-trunc',
          ],
        },
        'functions-datetime',
        {
          type: 'category',
          label: 'Numeric',
          collapsed: true,
          collapsible: true,
          link: {type: 'doc', id: 'functions-numeric'},
          items: [
            'functions/ceil',
            'functions/floor',
            'functions/round',
            'functions/trunc',
          ],
        },
        {
          type: 'category',
          label: 'String',
          collapsed: true,
          collapsible: true,
          link: {type: 'doc', id: 'functions-string'},
          items: [
            'functions/concat',
            'functions/contains',
            'functions/ends_with',
            'functions/length',
            'functions/ltrim',
            'functions/lower',
            'functions/regexp_like',
            'functions/replace',
            'functions/reverse',
            'functions/rtrim',
            'functions/search',
            'functions/split',
            'functions/starts_with',
            'functions/substr',
            'functions/trim',
            'functions/upper',
          ]
        },
        {
          type: 'category',
          label: 'Variant data',
          collapsed: true,
          collapsible: true,
          link: {type: 'doc', id: 'functions-variant'},
          items: [
            'functions/get',
            'functions/object_keys',
            'functions/parse_json',
            'functions/to_json',
            'functions/typeof',
          ],
        },
      ],
    },
  ]
};

export default sidebars;
